### ISSUE TITLE
接口已失效

### ISSUE THREAD

**Issue by chenshiforever** [yunv/wisdomtree#14]
https://appstudent.zhihuishu.com/appstudent/student/tutorial/getSaveLearningRecordToken
这个接口没找到改成啥了，求大佬解救

**Comment by chenshiforever** [comment]
这个接口猜测是改为了student/tutorial/getSaveStudyRecordToken，没帐号，测试不了，参数增加两个timeNote':1515340800,'uuid':uu
还有下面相应的saveStudyRecordToken也应该更改，这个接口参数不变~
哇，自问自答

**Comment by chenshiforever** [comment]
大佬教教我怎么脱壳新版的知到app，脱不掉后面更新接口就凉凉，我只能根据你的博客脱掉了旧版的智慧树网app，新版的用那个工具没脱下来

**Comment by yunv** [comment]
`getSaveLearningRecordToken`和`getSaveStudyRecordToken`是两个页面分别调用的，应该继续使用`getSaveLearningRecordToken`，它只有`versionKey`变了。然而我并不能测试
[脱壳参考](https://bbs.pediy.com/thread-219227.htm)

**Comment by chenshiforever** [comment]
getSaveLearningRecordToken这个接口已经没了。。被删掉了。。emmmm，你可以直接点击
https://appstudent.zhihuishu.com/appstudent/student/tutorial/getSaveLearningRecordToken
他已经自动重定向了。
