### ISSUE TITLE
api 报错。。。emmm

### ISSUE THREAD

**Issue by chenshiforever** [yunv/wisdomtree#16]
/student/exam/getExamQuestionIdFromTeacher

**Comment by yunv** [comment]
¯\_(ツ)_/¯

**Comment by chenshiforever** [comment]
解决办法，修改ua字符串，
`s.headers.update({
        'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Mobile/14G60 QQ/6.5.5.0 TIM/2.2.6.401 V1_IPH_SQ_6.5.5_1_TIM_D Pixel/750 Core/UIWebView Device/Apple(iPhone 6s) NetType/4G',
        'Accept-Encoding': 'gzip'})`
然后这个api传的数据改为`p = {'examId': exam_id}`
好了，尽量少用，，，，用多了又会被ban，好像他们已经开启了ban IP的功能，应该是几分钟内大量请求会被ban。。哈哈哈哈h
