### ISSUE TITLE
Crashes when trying to submit an exam not start yet

### ISSUE THREAD

**Issue by SykieChen** [yunv/wisdomtree#6]
It tried to submit an exam which is not opened yet, and it crashed.
Not a serious thing, it does not effect those opened exams.
![image](https://user-images.githubusercontent.com/5460009/31186686-eafa4978-a961-11e7-9bae-f93bc075eba8.png)
![image](https://user-images.githubusercontent.com/5460009/31186695-f74c1a9e-a961-11e7-812d-a69f00950302.png)

**Comment by violarulan** [comment]
same to me, although the result is good
